// export const apiRootUrl = "https://0571264e1618.ngrok.io"
// export const apiRootUrl = "http://localhost:5000"
export const apiRootUrl = "http://sunraystationers.com/api/"
export const ssClientCryptoSecretKey = "yOqHPAqgdG"
export const ssClientAuthFlagCookieKey = "a9K5J"
export const ssClientAuthCookieKey = "_jUkq5291cN411"
export const setUserDataCookieKey = "S_U"